---
- name: Create group and add user
  hosts: all
  tasks:
          - name: create group ibm
            group:
                    name: ibm
                    state: present
          - name: create user
            user:
                    name: ram
                    state: present
                    shell: /bin/bash
