---
- name: Create group and add user
  hosts: all
  tasks:
          - name: create group ibm
            group:
                    name: ibm
                    state: present
          - name: Add user ahar
            user:
                    name: ahar
                    state: present
